---
- name: Create Radiusadius Failed Vlan (enable mode commands)
  hosts: "{{ cisco_router }}"
  connection: network_cli
  gather_facts: no

  tasks:
    - name: ADD_ACL
      ios_config:
        lines:
          - access-list 1 permit any

    - name: "SAVE CONFIGURATION"
      register: save_config
      ios_command:
        commands:
          - "write memory"
