---
- name: ADD_NTP_Lo0 (enable mode commands)
  hosts: "{{ cisco_router }}"
  connection: network_cli
  gather_facts: no

  tasks:
    - name: ADD_NTP_Lo0
      ios_config:
        lines:
          - ntp server 192.168.200.1
          - int lo 0
          - ip address 1.1.1.1 255.255.255.255

    - name: "SAVE CONFIGURATION"
      register: save_config
      ios_command:
        commands:
          - "write memory"
     
    - name: Sending an e-mail using 51talk SMTP servers
      mail:
        host: "{{ mail_server }}"
        port: 587
        username: "{{ mail_user }}"
        password: "{{ mail_password }}"
        to: ITSH <"{{ mail_to }}">
        subject: Ansible-report
        body: Router "{{ cisco_router }}" has been successfully provisioned.
      delegate_to: localhost

