---
- name: ADD_NTP_Lo0 (enable mode commands)
  hosts: "{{ cisco_router }}"
  connection: network_cli
  gather_facts: no

  tasks:
    - name: ADD_NTP_Lo0
      ios_config:
        lines:
          - ntp server 192.168.200.1
          - int lo 0
          - ip address 1.1.1.1 255.255.255.255

    - name: "SAVE CONFIGURATION"
      register: save_config
      ios_command:
        commands:
          - "write memory"
     
    - name: send mail
      mail:
       host: 127.0.0.1
       port: 25
       sender: nmsalert@51talk.com
       to: ITSH <itsh@51talk>
       subject: Report for {{ cisco_router }}
       body: 'Server {{ cisco_router }} has bene updated'
      delegate_to: localhost
