---
- name: Create Radiusadius Failed Vlan (enable mode commands)
  hosts: "{{ cisco_router }}"
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Create Radiusadius Failed Vlan
      ios_config:
        lines:
          - vlan 52
          - name Radius_Failed_Vlan
        backup: yes

    - name: Save running to startup when modified
      ios_config:
        save_when: modified
