---
- name: Create Radiusadius Failed Vlan (enable mode commands)
  hosts: all
  gather_facts: false
  connection: network_cli
  become: yes
  
  tasks:
    - name: Create Radiusadius Failed Vlan
      ios_config:
        lines:
          - vlan 52
          - name Radius_Failed_Vlan

      register: print_output

    -  debug: var=print_output

    - name: "SAVE CONFIGURATION"
      register: save_config
      ios_command:
        commands:
          - "write memory"

      register: print_output

    -  debug: var=print_output
    
  vars:
    ansible_network_os: ios
  
